"""JANATPMP — Multipage Gradio application with MCP server.

Sovereign multipage architecture: one process, one port, one MCP surface.
Routes: / (Projects+Work), /knowledge, /admin, /chat.
"""

import sys
import logging

# Fix Windows cp1252 console crash on Gradio's emoji output
if sys.platform == "win32":
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    sys.stderr.reconfigure(encoding="utf-8", errors="replace")

from services.log_config import setup_logging
setup_logging()
logger = logging.getLogger(__name__)

import gradio as gr
from mcp_registry import ALL_MCP_TOOLS
from services.startup import (
    initialize_core, initialize_services,
    start_auto_ingest, is_auto_ingest_complete,
)
from pages.projects import build_page
from pages import chat as chat_page
from pages import knowledge as knowledge_page
from pages import admin as admin_page
from janat_theme import JanatTheme, JANAT_CSS

# --- Platform initialization (strict order) ---
initialize_core()       # DB, settings, cleanup, Janus (blocking, fast)
initialize_services()   # Qdrant, Slumber, Neo4j (optional, graceful degrade)
start_auto_ingest()     # Background thread (non-blocking)

# --- Startup banner ---
_STARTUP_BANNER_HTML = """
<div style="
    background: linear-gradient(135deg, #0a0a0a 0%, #1a001a 100%);
    border: 1px solid #00FFFF;
    border-radius: 8px;
    padding: 16px 24px;
    margin: 12px 0;
    text-align: center;
    font-family: 'Rajdhani', sans-serif;
">
    <span style="
        font-family: 'Orbitron', sans-serif;
        color: #00FFFF;
        font-size: 1.1rem;
        letter-spacing: 0.1em;
    ">JANUS</span>
    <span style="
        color: #808080;
        font-size: 0.95rem;
        margin-left: 8px;
    ">is getting ready for work...</span>
    <div style="
        margin-top: 8px;
        height: 2px;
        background: linear-gradient(90deg, transparent, #00FFFF, transparent);
        animation: janus-pulse 2s ease-in-out infinite;
    "></div>
</div>
<style>
    @keyframes janus-pulse {
        0%, 100% { opacity: 0.3; }
        50% { opacity: 1; }
    }
</style>
"""


def _check_ingest_status():
    """Poll background auto-ingest. Dismiss banner and stop timer when done."""
    if is_auto_ingest_complete():
        return gr.HTML(visible=False), gr.Timer(active=False)
    return gr.skip(), gr.skip()


# --- Build multipage application ---
# Navbar is auto-generated by demo.route() — restyled as branded header via JANAT_CSS.
with gr.Blocks(title="JANATPMP") as demo:
    gr.Navbar(main_page_name="Projects")

    # Startup status banner (dismissed when background auto-ingest completes)
    startup_banner = gr.HTML(value=_STARTUP_BANNER_HTML, visible=True)
    ingest_timer = gr.Timer(value=2.0, active=True)

    build_page()

    # Register all MCP tools (71 functions from mcp_registry.py)
    for tool_fn in ALL_MCP_TOOLS:
        gr.api(tool_fn)

    # Banner dismissal wiring
    ingest_timer.tick(
        _check_ingest_status,
        outputs=[startup_banner, ingest_timer],
        api_visibility="private",
    )

# --- Sovereign Knowledge route ---
with demo.route("Knowledge", "/knowledge"):
    gr.Navbar(main_page_name="Projects")
    knowledge_page.build_knowledge_page()

# --- Sovereign Admin route ---
with demo.route("Admin", "/admin"):
    gr.Navbar(main_page_name="Projects")
    admin_page.build_admin_page()

# --- Sovereign Chat route ---
with demo.route("Chat", "/chat"):
    gr.Navbar(main_page_name="Projects")
    chat_page.build_chat_page()

if __name__ == "__main__":
    demo.launch(
        mcp_server=True,
        server_name="0.0.0.0",
        theme=JanatTheme(),
        css=JANAT_CSS,
        allowed_paths=["assets"],
        show_error=True,
        # Footer hidden via CSS in janat_theme.py (Gradio 6.6.0 has no show_footer param)
    )
