"""JANATPMP — Multipage Gradio application with MCP server.

Hybrid architecture: monolith at / (Projects, Work, Knowledge, Admin)
plus Sovereign Chat at /chat via demo.route().
"""

import sys
import logging

# Fix Windows cp1252 console crash on Gradio's emoji output
if sys.platform == "win32":
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    sys.stderr.reconfigure(encoding="utf-8", errors="replace")

from services.log_config import setup_logging, cleanup_old_logs
setup_logging()
logger = logging.getLogger(__name__)

import gradio as gr
from db.operations import (
    init_database, cleanup_cdc_outbox,
    # MCP-exposed operations
    create_item, get_item, list_items, update_item, delete_item,
    create_task, get_task, list_tasks, update_task,
    create_document, get_document, list_documents,
    search_items, search_documents,
    create_relationship, get_relationships,
    get_stats, get_schema_info,
    backup_database, reset_database, restore_database, list_backups,
    get_domains, get_domain, create_domain, update_domain,
)
from db.chat_operations import (
    create_conversation, get_conversation, get_conversation_by_uri,
    list_conversations, update_conversation, delete_conversation,
    search_conversations, add_message, get_messages,
)
from services.claude_import import import_conversations_json
from services.vector_store import (
    search as vector_search, search_all as vector_search_all,
    recreate_collections,
)
from services.bulk_embed import embed_all_documents, embed_all_messages, embed_all_domains
from pages.projects import build_page
from pages import chat as chat_page
from janat_theme import JanatTheme, JANAT_CSS

# Initialize database and settings BEFORE building UI
init_database()
from services.settings import init_settings
init_settings()
cleanup_old_logs()
cleanup_cdc_outbox()
logger.info("Database and settings initialized")

# Initialize vector store collections (safe if Qdrant not running)
try:
    from services.vector_store import ensure_collections
    ensure_collections()
except Exception:
    logger.warning("Qdrant not available -- vector search disabled")

# Build multipage application
# Navbar is auto-generated by demo.route() — restyled as branded header via JANAT_CSS.
with gr.Blocks(title="JANATPMP") as demo:
    gr.Navbar(main_page_name="Dashboard")
    build_page()

    # Expose ALL operations as MCP tools
    gr.api(create_item)
    gr.api(get_item)
    gr.api(list_items)
    gr.api(update_item)
    gr.api(delete_item)
    gr.api(create_task)
    gr.api(get_task)
    gr.api(list_tasks)
    gr.api(update_task)
    gr.api(create_document)
    gr.api(get_document)
    gr.api(list_documents)
    gr.api(search_items)
    gr.api(search_documents)
    gr.api(create_relationship)
    gr.api(get_relationships)
    gr.api(get_stats)
    gr.api(get_schema_info)
    gr.api(backup_database)
    gr.api(reset_database)
    gr.api(restore_database)
    gr.api(list_backups)

    # Domain operations (R8)
    gr.api(get_domains)
    gr.api(get_domain)
    gr.api(create_domain)
    gr.api(update_domain)

    # Chat operations (Phase 4B)
    gr.api(create_conversation)
    gr.api(get_conversation)
    gr.api(list_conversations)
    gr.api(update_conversation)
    gr.api(delete_conversation)
    gr.api(search_conversations)
    gr.api(add_message)
    gr.api(get_messages)
    gr.api(get_conversation_by_uri)

    # Import pipeline (Phase 5)
    gr.api(import_conversations_json)

    # RAG pipeline (R9: ATLAS two-stage search + embedding)
    gr.api(vector_search)
    gr.api(vector_search_all)
    gr.api(embed_all_documents)
    gr.api(embed_all_messages)
    gr.api(embed_all_domains)
    gr.api(recreate_collections)

# --- Sovereign Chat route (outside main Blocks context) ---
with demo.route("Chat", "/chat"):
    gr.Navbar(main_page_name="Dashboard")
    chat_page.build_chat_page()

if __name__ == "__main__":
    demo.launch(
        mcp_server=True,
        server_name="0.0.0.0",
        theme=JanatTheme(),
        css=JANAT_CSS,
        allowed_paths=["assets"],
    )
